#%RAML 1.0 NamedExample
example:
  {
    "Sheet1":
    [
      {
      "Id":123,
      "Name":"Jayesh",
      "Contact":9079611709,
      "Address":"Rajasthan"
      },
      {
      "Id":1234,
      "Name":"Paliwal",
      "Contact":9079611709,
      "Address":"Rajasthan"
      }
    ]
  }